FROM node:12

RUN apt-get -y update \
  && apt-get install -y git

RUN npm install -g @vue/cli

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8080

#USER node

CMD ["yarn", "serve"]