version: '3'

services:
  tms:
    container_name: tms
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - node_modules:/app/node_modules
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
volumes:
  node_modules:
